
BOOST_CFLAGS := \
	-D_STLP_USE_DYNAMIC_LIB=1 \
	-DBOOST_ATOMIC_STATIC_LINK=1 \
	-DBOOST_NO_CXX11_NULLPTR \
	-DBOOST_NO_CXX11_RVALUE_REFERENCES \
	-DBOOST_NO_CXX11_VARIADIC_TEMPLATES \


BOOST_INCLUDES := \
	external/boost-root/boost_1_66_0
