rm -rf ./poly_collection # 1.2M	
rm -rf ./mp11 # 1.3M	
rm -rf ./exception # 1.3M	
rm -rf ./lambda # 460K	
rm -rf ./locale # 7.0M	
# rm -rf ./any # 112K	
rm -rf ./dll # 472K	
# rm -rf ./typeof # 176K	
rm -rf ./property_map # 212K	
# rm -rf ./atomic # 272K	
rm -rf ./multi_index # 1.9M	
rm -rf ./interprocess # 2.9M	
rm -rf ./detail # 308K	
rm -rf ./units # 1.2M	
rm -rf ./msm # 5.0M	
# rm -rf ./lockfree # 200K	
rm -rf ./log # 11M	
rm -rf ./multi_array # 584K	
rm -rf ./parameter # 628K	
rm -rf ./iterator # 3.9M	
rm -rf ./assign # 324K	
rm -rf ./disjoint_sets # 48K	
rm -rf ./config # 3.6M	
rm -rf ./qvm # 6.5M	
rm -rf ./iostreams # 2.3M	
rm -rf ./functional # 808K	
rm -rf ./asio # 6.9M	
rm -rf ./property_tree # 488K	
rm -rf ./utility # 824K	
rm -rf ./intrusive # 3.3M	
rm -rf ./algorithm # 5.4M	
rm -rf ./wave # 3.5M	
rm -rf ./filesystem # 2.0M	
rm -rf ./integer # 376K	
rm -rf ./bind # 752K	
rm -rf ./function # 284K	
rm -rf ./mpi # 840K	
rm -rf ./serialization # 2.3M	
rm -rf ./container # 3.2M	
rm -rf ./format # 252K	
rm -rf ./array # 112K	
rm -rf ./date_time # 2.0M	
rm -rf ./chrono # 1.6M	
rm -rf ./type_index # 256K	
rm -rf ./align # 100K	
rm -rf ./signals2 # 468K	
rm -rf ./core # 980K	
rm -rf ./crc # 76K	
rm -rf ./sort # 4.8M	
rm -rf ./test # 8.8M	
rm -rf ./geometry # 21M	
rm -rf ./polygon # 6.9M	
rm -rf ./flyweight # 772K	
rm -rf ./rational # 188K	
rm -rf ./local_function # 1.7M	
rm -rf ./graph_parallel # 2.2M	
rm -rf ./metaparse # 7.4M	
rm -rf ./predef # 212K	
rm -rf ./tokenizer # 136K	
rm -rf ./phoenix # 3.2M	
rm -rf ./range # 3.9M	
rm -rf ./process # 612K	
rm -rf ./pool # 3.2M	
rm -rf ./circular_buffer # 644K	
rm -rf ./spirit # 17M	
rm -rf ./program_options # 636K	
rm -rf ./uuid # 216K	
rm -rf ./scope_exit # 476K	
rm -rf ./ratio # 440K	
rm -rf ./callable_traits # 1.3M	
rm -rf ./optional # 2.5M	
rm -rf ./coroutine # 1.1M	
rm -rf ./ptr_container # 1.2M	
rm -rf ./tuple # 228K	
rm -rf ./heap # 284K	
rm -rf ./fiber # 5.1M	
rm -rf ./smart_ptr # 1.9M	
rm -rf ./numeric # 9.4M	
rm -rf ./winapi # 116K	
rm -rf ./convert # 1.5M	
rm -rf ./unordered # 1.2M	
rm -rf ./lexical_cast # 336K	
rm -rf ./compute # 5.0M	
rm -rf ./multiprecision # 8.3M	
rm -rf ./assert # 160K	
rm -rf ./python # 6.5M	
rm -rf ./endian # 620K	
rm -rf ./hana # 19M	
rm -rf ./graph # 12M	
rm -rf ./gil # 7.5M	
rm -rf ./fusion # 6.0M	
rm -rf ./proto # 1.7M	
rm -rf ./statechart # 2.1M	
rm -rf ./logic # 84K	
rm -rf ./vmd # 3.6M	
rm -rf ./stacktrace # 216K	
rm -rf ./random # 1.3M	
rm -rf ./static_assert # 100K	
# rm -rf ./.git # 215M	
rm -rf ./compatibility # 28K	
rm -rf ./type_erasure # 608K	
rm -rf ./context # 1.7M	
rm -rf ./accumulators # 836K	
rm -rf ./signals # 328K	
rm -rf ./math # 76M	
rm -rf ./regex # 3.8M	
rm -rf ./tti # 1.6M	
rm -rf ./xpressive # 996K	
rm -rf ./variant # 496K	
rm -rf ./beast # 21M	
rm -rf ./mpl # 6.5M	
rm -rf ./move # 628K	
rm -rf ./bimap # 3.1M	
rm -rf ./io # 96K	
rm -rf ./thread # 3.6M	
rm -rf ./system # 260K	
rm -rf ./dynamic_bitset # 232K	
rm -rf ./throw_exception # 92K	
rm -rf ./icl # 11M	
rm -rf ./type_traits # 5.3M	
rm -rf ./foreach # 164K	
rm -rf ./conversion # 72K	
rm -rf ./preprocessor # 2.8M	
rm -rf ./coroutine2 # 736K	
rm -rf ./concept_check # 436K	
rm -rf ./function_types # 544K	
rm -rf ./timer # 196K	

